### PR TITLE
Upgrade react typings

### LINKED ISSUE #135: Throwing type errors with "@types/react": "^16.4.6" (latest)
screenshot_20180703_120757

### PR DESCRIPTION
**Pull request by ydlamba**
Fixes #135.

### CODE REVIEW

**Comment by ydlamba** [comment]
@domoritz This will fix the upgrade react types issue in the vega editor.

**Comment by domoritz** [comment]
Hmm, can you instead just update the yarn.lock file only?

**Comment by ydlamba** [comment]
PR has been updated.

**Comment by domoritz** [comment]
I don't see why a release is necessary. You can use the version of typings that you want.

**Pull request merged**
