### PR TITLE
upgrade monaco-editor 0.10.0

### PR DESCRIPTION
**Pull request by jarandrew**

### CODE REVIEW

**Comment by jarandrew** [comment]
@expobrain thanks for merging, did you publish new version to npm.org as well?

**Comment by expobrain** [comment]
@domoritz you are right. 

Also, on second thought I think it's better to keep the peer dep version as lower as possible to increase the compatibility (aka `react-monaco-editor` will be compatible with `monaco-editor` o.9 or later).

@jarandrew did you solved your issue with the @domoritz suggestion?

@domoritz do you agree on me reverting the merge?

**Comment by domoritz** [comment]
I'm actually okay with upgrading the monaco version since it makes it easier for us to guarantee that things work. If somebody wants to use an old version, they shouldn't upgrade react monaco editor.

**Comment by expobrain** [comment]
@domoritz ok, I'll also push the new version as well.

**Pull request merged**
