### PR TITLE
Use prop-types package (deprecated in React)

### PR DESCRIPTION
**Pull request by Dominionized**

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
Is there a timeline for merging this PR?

**Comment by domoritz** [comment]
Would love to see this merged and released.

**Comment by piotrpMSFT** [comment]
Yep, me too!

**Comment by webdeveloperpr** [comment]
Need this PR merged so I can use in the newer version of react

**Comment by domoritz** [comment]
Is this project dead? I'm already maintaining my own fork at https://github.com/vega/react-monaco-editor. I don't have the time to maintain a fork and push to NPM regularly so I wonder whether someone else can consolidate all the PRs in a fork. 

@superRaytin, let us know if you don't have time to maintain this project anymore.

**Comment by superRaytin** [comment]
@domoritz yeah, i dont have time to maintain this project, would you like to be a collaborator?

**Comment by expobrain** [comment]
@superRaytin I can lend an help too

**Comment by superRaytin** [comment]
@expobrain thanks, i have invited you

**Comment by domoritz** [comment]
@superRaytin, thanks for the invite. I'm happy to merge back our changes. Do you have the time to make npm releases?

**Comment by webdeveloperpr** [comment]
Awesome, glad this is happening!

**Comment by superRaytin** [comment]
@domoritz @expobrain  due to busy work, i can not guarantee to make npm release timely. what's your npm user name? I can add you guys to npm owners. thanks!

**Comment by domoritz** [comment]
@superRaytin It's `domoritz`. See https://www.npmjs.com/~domoritz

**Comment by superRaytin** [comment]
@domoritz done

**Comment by expobrain** [comment]
@superRaytin mine is https://www.npmjs.com/~expobrain

**Comment by superRaytin** [comment]
@expobrain done

**Comment by expobrain** [comment]
@superRaytin I cannot see @domoritz in the list of reviewers, it should appear automatically or you need to add it manually?

**Comment by superRaytin** [comment]
hmmm... @domoritz you should click this link https://github.com/superRaytin/react-monaco-editor/invitations to accept the invitation.

**Pull request merged**
