### PR TITLE
Fixes #127

### LINKED ISSUE #127: Update TypeScript definitions
I just found these definitions on DT:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-monaco-editor/index.d.ts

As `react-monaco-editor` now ships with its definitions (which is the preferred way), we may add some stuff of the awesome work of @jnetterf and [remove the definitions from DT](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package) to avoid clashes.

### PR DESCRIPTION
**Pull request by nikeee**

### CODE REVIEW

**Comment by domoritz** [comment]
Sweet. Do you think there is a way to extend the Monaco typings directly?

**Comment by nikeee** [comment]
What do you mean by "extend"?

**Comment by nikeee** [comment]
I think this is what we are already doing. We are re-exporting some of the interfaces of monaco-editor by saying `import * as monacoEditor from "monaco-editor";` and using monacoEditor in the type definitions (like in `monacoEditor.editor.IEditorConstructionOptions;`). This works because - as you said - the editor itself is written in TS and also ships with its definitions. The end user will have the definitions of monaco-editor and react-monaco-editor because both ship them in the npm package. Everything we have written in the definitions of this repo is only for the stuff in this repository - we are not re-inventing the wheel of monaco's definitions, as far as I can tell.

Or did I get your question wrong?

**Comment by domoritz** [comment]
That makes sense. I was just wondering whether there are some types for `language`, `requireConfig`, or `theme` but it's not a big deal. Thanks for you PR!

**Comment by nikeee** [comment]
>  I was just wondering whether there are some types for language, requireConfig

These come from the options of the component: https://github.com/superRaytin/react-monaco-editor#properties
I think they are just passed to `monaco.editor.create`, except some of them like `context`, `editorWill*` and so on.

We could do something like `interface MonacoEditorProps extends monaco editor IEditorConstructionOptions` (see https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html). But I don't know whether we can set *every* property of `IEditorConstructionOptions` directly as an editor prop (havent looked at the component's code).
Also, there is the dedicated `options` property of the component, which is also a `IEditorConstructionOptions`.

We tighten this more, using something like these:
```TypeScript
// ...
language: monaco.editor.IEditorConstructionOptions["language"]` (which resolves to `string`)
// ...
```

**Comment by nikeee** [comment]
It is there and has the type of monaco's options:
https://github.com/superRaytin/react-monaco-editor/blob/master/src/index.d.ts#L65

However, one can do this:
```TypeScript
<MonacoEditor value={"foo"} options={{value: "bar"}} />
```
Looking at the source, the `foo` should get overridden by `bar`: https://github.com/superRaytin/react-monaco-editor/blob/master/src/editor.js#L74-L76

Thats not a problem on the typing perspective. Its just that the value can be set using multiple ways.

But it's not a problem anyways.

**Pull request merged**
